# Generated by Django 4.1.5 on 2023-02-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_measurements_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='timeStamp',
            field=models.CharField(default='2023101000000', max_length=50),
        ),
    ]
