# Generated by Django 4.1.5 on 2023-01-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='timeStamp',
            field=models.CharField(default='2023121172241', max_length=50),
        ),
    ]
