# Generated by Django 4.1.5 on 2023-03-05 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_farm_status'),
        ('analytics', '0003_alter_measurements_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='water_used',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_amnt', models.FloatField()),
                ('date', models.DateField()),
                ('t1', models.TimeField()),
                ('t2', models.TimeField()),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wt_farm_name', to='home.farm')),
            ],
        ),
    ]
