# Generated by Django 4.1.5 on 2023-03-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_water_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='description',
            field=models.CharField(default='Analyzer Online', max_length=200),
            preserve_default=False,
        ),
    ]
