# Generated by Django 4.1.5 on 2023-03-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_farm_crop'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='farm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mg_farm_name', to='home.farm'),
        ),
    ]
