# Generated by Django 4.1.5 on 2023-03-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
        ('home', '0002_alter_farm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='crop',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cult_crop', to='crops.crops'),
            preserve_default=False,
        ),
    ]
